version: '3'

services:
    main-website:
        build: .
        ports:
            - 8080:80
    stock-market-app:
        build: StockMarketApplication
        ports:
            - 8081:80
    recipe-app:
        build: RecipeApp
        ports:
            - 8082:80
    recipe-app-db:
        image: postgres
        environment:
            - POSTGRES_DB=RecipeApp
            - POSTGRES_PASSWORD=password
        volumes:
            - ./RecipeApp/postgres/data:/var/lib/postgresql/data
        ports:
            - 7072:5432
    pde-solver:
        build: PDESolver
        ports:
            - 8083:80
