version: '3'

services:
    main-website:
        build: .
        ports:
            - 8080:80
    stock-market-app:
        build: StockMarketApplication
        ports:
            - 8081:80
    recipe-app:
        build: RecipeApp
            - 8082:80
